blocklist:
  - "00000000-0000-0000-0000-000000000000" # Prevent accidental deletion in wrong subscription

regions:
  - global
  - all

resource-types:
  excludes:
    - Application
    - ApplicationFederatedCredential
    - ServicePrincipal
    - SubscriptionRoleAssignment

accounts:
  "fa193ac0-9c06-4111-bf55-341e4db193d3":
    filters:
      ResourceGroup:
        - property: tag:CCC_INFRA_DONT_DELETE
          type: exact
          value: "true"
