blocklist:
  - "00000000-0000-0000-0000-000000000000" # Prevent accidental deletion in wrong subscription

regions:
  - global
  - all

resource-types:
  excludes:
    - Application
    - ApplicationFederatedCredential
    - ServicePrincipal
    - SubscriptionRoleAssignment

accounts:
  "c1cedd8e-bf91-4d7d-a4cc-45700402a2a1":
    filters:
      ResourceGroup:
        - property: tag:CCC_INFRA_DONT_DELETE
          type: exact
          value: "true"
